name: MCME-Music
main: com.mcmiddleearth.mcmemusic.Main
version: 1.1
author: Gilan
api-version: 1.16
loadbefore: [JukeBox]
depend: [WorldEdit]

commands:
  music:
    description: Create Music Region
    usage: /music create|on|off

permissions:
  mcmemusic.manage:
    default: op
    children:
      mcmemusic.listen: true
  mcmemusic.listen:
    default: op